---
# tasks file for nss-module

- name: list nss modules
  block:
  - &list_module
    name: list nss modules
    command: modutil -dbdir {{ nss_module_nssdb | quote }} -list
    register: nss_module_probe
    changed_when: no
    check_mode: no
  rescue:
  - name: fail for missing nssdb or other failure
    fail:
      msg: nssdb creation was not requested or modutil -list failed unexpectedly
    when: not nss_module_create_db or nss_module_probe.rc != 46

  - name: create folder for nssdb
    file:
      path: "{{ nss_module_nssdb }}"
      state: directory
      mode: '0755'

  - name: create nssdb
    command: modutil -dbdir {{ nss_module_nssdb | quote }} -create

  - name: list nss modules (again)
    <<: *list_module

  always:
  - debug:
      msg: "{{ nss_module_lib_info }}"
      #{{ r.stdout }}
    #{{ nss_module_probe.stdout.split('\n\n'.decode('string_escape')) | map('regex_search', '(?s)^ ? ?[0-9]+\. (?P<module>.*?)$.*?$\s+library name: (?P<lib>.*?)$', multiline=True, groupdict=True) | select('mapping') |list }}


  vars:
    nss_module_lib_info: >-
      {{ nss_module_probe.stdout.split('\n\n'.decode('string_escape'))
      | map('regex_search', nss_module_re_module_lib, multiline=True, groupdict=True)
      | select('mapping') | list }}
    nss_module_re_module_lib: >-
      (?s)^ ? ?[0-9]+\. (?P<module>.*?)$.*?$\s+library name: (?P<lib>.*?)$
    nss_module_name: Root Certs
    nss_module_lib: libnssckbi.so
    nss_module_nssdb: /etc/pki/nssdb
    nss_module_create_db: yes
