---
# tasks file for nss-module

- name: list nss modules
  block:
  - &list_module
    name: list nss modules
    command: modutil -dbdir {{ nss_module_nssdb | quote }} -list
    check_mode: no
    register: nss_module_probe
    changed_when: no
  rescue:
  - name: fail for missing nssdb or other failure
    fail:
      msg: nssdb creation was not requested or modutil -list failed unexpectedly
    when: not nss_module_create_db or nss_module_probe.rc != 46

  - name: create folder for nssdb
    file:
      path: "{{ nss_module_nssdb }}"
      state: directory
      mode: '0755'

  - name: create nssdb
    command: >-
      {{ nss_module_echo_check }}modutil -dbdir {{ nss_module_nssdb | quote }} -create
    check_mode: no

  - <<: *list_module
    ignore_errors: "{{ ansible_check_mode }}"


- name: delete module from db
  command: >-
    {{ nss_module_echo_check }}modutil -dbdir {{ nss_module_nssdb | quote }}
    -delete {{ nss_module_name | quote }}
  check_mode: no
  when: >-
    nss_module_lib_info | selectattr('module', 'match', (nss_module_name | regex_escape) ~ '$')
    | rejectattr('lib', 'match', (nss_module_lib | regex_escape) ~ '$') | list | length
    or
    nss_module_state == 'absent' and
    (nss_module_lib_info | selectattr('module', 'match', (nss_module_name | regex_escape) ~ '$')
    | list | length)

- name: add module to db
  command: >-
    {{ nss_module_echo_check }}modutil -dbdir {{ nss_module_nssdb | quote }}
    -add {{ nss_module_name | quote }} -libfile {{ nss_module_lib | quote }}
  check_mode: no
  when: >-
    nss_module_lib_info | selectattr('module', 'match', (nss_module_name | regex_escape) ~ '$')
    | selectattr('lib', 'match', (nss_module_lib | regex_escape) ~ '$') | list | length == 0
    and nss_module_state == 'present'
